### ISSUE TITLE
Themes and plugins won't show in settings.

### ISSUE THREAD

**Issue by artelse** [nextcloud/cms_pico#104]
I've been trying to get themes and plugins to work. I installed the folders in `nextcloud/data/appdata_ocy453crs20e/cms_pico/themes` and `../plugins` but it won't show up in settings. Running NC17 and Pico 1.0.3. Any ideas?
Edit: permissions are set according to parent data folder.

**Comment by iStefo** [comment]
Since 1.0.3, themes are now in `/apps/cms_pico/appdata/themes`, try copying the files there.

However, I have not yet understood what appdata_public/themes is about, since that folder seems to get recreated when loading a theme, but no all files are copied there, leaving me with broken resources (styles, scripts...)

**Comment by artelse** [comment]
Thanks for the input. Have copied the folder/files, but the theme is still not recognised. Also my test website show my index.md, but in the theme, no navigation links or whatever are shown. I might have some other misconfiguration?

**Comment by PhrozenByte** [comment]
You do **not** copy files to `/apps/cms_pico/appdata/themes` yourself, Pico CMS for Nextcloud takes care of this when publishing themes. As stated in the description on the admin settings page, you must upload your themes (i.e. a theme folder) to `/data/appdata_*/cms_pico/themes` and publish the theme via the app's admin settings page. If the theme doesn't show up in the list there you must check your file permissions; Nextcloud can't read the contents of the directory then. If the app doesn't copy all files make sure that the file permissions of all files and dirs are right. Please note that you can't add custom themes called `default` (i.e. `/data/appdata_*/cms_pico/themes/default`), since there's already a system theme of the same name.

**Comment by iStefo** [comment]
@PhrozenByte thank you for the explanation. I think there was some bug in the older version (or at least some quirk in combination with the way I rewrite URLs) that required me to copy the theme to `/apps/cms_pico/Pico`.

But at least since 1.0.3, loading the theme from `/data/appdata_*/cms_pico` works fine for me 👍

**Comment by artelse** [comment]
@PhrozenByte Got the themes and plugins working now. Thanks for the help, in my case had a NC misconfiguration and uploaded into the wrong data directory.
The remaining issue is that the generated website doesn't show any other files than the index.md content. Other files in the website folder are ignored and don't show up in navigation. 
Any idea why that happens? Thanks much!

**Comment by PhrozenByte** [comment]
We solved this via [#picocms on Freenode IRC](https://webchat.freenode.net/?channels=%23picocms) already, just for record:

>  The remaining issue is that the generated website doesn't show any other files than the index.md content. Other files in the website folder are ignored and don't show up in navigation.

1. Switch to Pico's default theme. If it works there it's an issue with your custom theme. Carefully read the theme's `README.md` and docs. If there are sample contents, check out the theme's sample contents, too.

2. Make sure your website's `content` directory is valid:

    1. The navigation of Pico's default theme (and most other themes) lists the pages `content/*.md` and `content/*/index.md` only on purpose. Make sure there are actually pages to show.

    2. Make sure that your `*.md` files have a title. Check your page's YAML header, there must be a `title` meta header like the following:

        ```md
        ---
        title: My awesome page
        ---
        ```

    3. Make sure that no path components of a page's full path starts with a `_` (i.e. neither your page's file name nor the name of any directory starts with a `_`). Those pages are explicitly hidden.
