### ISSUE TITLE
%variables% not rendered when used in the meta section

### ISSUE THREAD

**Issue by leolivier** [nextcloud/cms_pico#132]
Hi,
I dont't know if it's a bug or request for improvement but I can't get the following working:
I'm trying to use the [clean-blog theme](http://picocms.org/themes/#entry-clean_blog) which contains:

`            <header class="intro-header" style="background-image: {% if meta.img %} url({{ meta.img }}) {% else %} url('{{ theme_url }}/img/home-bg.jpg'){% endif %};">
`

So I added at the top of my page something like:
```
---
Title: my title 
...
Img: %assets_url%/mybackground.jpg
---
```
But this is rendered as:
`    <header class="intro-header" style="background-image:  url(%assets_url%/mybackground.jpg) ;">
`

Furthermore, the assets url cannot be "guessed", it's built like "/sites/yourblog/assets-5ee50a2b62a5e/" so I'm not found to hardcode this in my page...

**Comment by PhrozenByte** [comment]
A theme must use Pico's `url` Twig filter if it wants to replace URL placeholders in variables, like

```twig
 <header class="intro-header" style="background-image: {% if meta.img %} url({{ meta.img|url }}) {% else %} url('{{ theme_url }}/img/home-bg.jpg'){% endif %};">
```

> Furthermore, the assets url cannot be "guessed", it's built like "/sites/yourblog/assets-5ee50a2b62a5e/" so I'm not found to hardcode this in my page...

You can fall back using `/sites/yourblock/assets/` - the `5ee50a2b62a5e` part is discarded anyway since its only purpose is to enable client-side caching.

Anyway, I'd recommend modifying the theme to fit your needs (i.e. adding the `url` Twig filter).

**Comment by leolivier** [comment]
Great @PhrozenByte , I was confident there was something simple to do to solve this issue.
Despite this, I think that all the themes published on the pico site should be checked so that we don't have to change this by ourselves. 
Also for the nextcloud version of pico_cms, where should I change things? I mean, I did some changes in a directory named .../apps/cms_pico/appdata_public/themes/mPfTlnz3ym/clean-blog but looking at what you're saying above, I'm not sure anymore that this is not also a caching directory...
As there is no separate documentation for the nextcloud version of pico cms, this kind of question has no documented answer (at least not that I could find)...

**Comment by PhrozenByte** [comment]
>  Despite this, I think that all the themes published on the pico site should be checked so that we don't have to change this by ourselves.

Since time is very limited this would basically mean to remove that page altogether. I'll likely be forced to do this sooner or later... Pico and Pico CMS for Nextcloud have thousands of users combined and I'm always telling people that help is very appreciated, but unfortunately I'm still doing everything by myself.

> Also for the nextcloud version of pico_cms, where should I change things?

This is documented directly in Pico CMS for Nextcloud on the admin settings page below the "Custom themes" section. It's basically the same as adding a new custom theme: You must edit your theme files below `data/appdata_*/cms_pico/themes/clean-blog` and then hit the "Reload" button of the custom theme.

>  As there is no separate documentation for the nextcloud version of pico cms, this kind of question has no documented answer (at least not that I could find)...

Pico's `url` Twig filter is documented on http://picocms.org/docs/. Using the functions Pico provides is up to the 3rd-party theme developer. Most themes were written for previous versions of Pico, a whole bunch for Pico 0.8 (released in 2013). We try to preserve backwards compatibility whenever possible, but this comes with the risk that theme developers don't see a reason to update their themes to use the latest features. Pico's `url` Twig filter was introduced with Pico 2.1.

**Comment by leolivier** [comment]
Thanks for the support @PhrozenByte .
I fully understand it's hard for you to manage this all alone as it's not part of the project itself. 
I'll try to put some issues (or even PRs) in the github projects of the themes I tested to get things progress.
Concerning the documentation (the French one at least), the admin page does not speak of changing things in the installed themes/plugins/... it only speaks of installing new things. It might be worth adding one sentence ( the one you wrote above) to explain this...

**Comment by leolivier** [comment]
👍 Thanks for the change.
I created 2 PRs on the url filter on clean-blog and dimension and they are already integrated 👍
