### ISSUE TITLE
Is it possible, as user, to modify themes?

### ISSUE THREAD

**Issue by StCyr** [nextcloud/cms_pico#139]
I've installed the [ethereal theme](https://github.com/BesrourMS/ethereal). 

This theme ships with several pictures that I'd like to adapt to the website I'm trying to build. 

Is this possible as a user to change these pictures?

**Comment by PhrozenByte** [comment]
Simply replace the files by images you want to use.

**Comment by StCyr** [comment]
well, I've found how to that.

The answer to my question "Is it possible, as user, to modify themes?" is: as user, it is not possible to modify themes: one needs filesystem access to modify themes.

And, you @PhrozenByte have somehow answered to my question "Is this possible as a user to change these pictures?"

The thing is: It's currently difficult (not impossible) to change the images because modifying the yaml in the .md files is hindered by the Text app that renders them, while one needs raw access to them to modify the yaml (so, the trick is to modify the .md files localy with your favorite text editor rather than within the browser)

**Comment by PhrozenByte** [comment]
You can (and should) modify themes to fit your needs. In this case you'll have to modify the theme in a way that you can change the image's URL, e.g. by using a `<img>` element instead of a `background-image` CSS rule on the body element. Same for any other image you want to change. You can then use a meta header pointing to a custom URL, e.g.

```twig
<img src="{{ meta.bg_image|url ?? "bg.jpg" }}" alt="" />
```

Nextcloud's Text app unfortunately is incompatible with Pico CMS for Nextcloud. Either use Nextcloud's plain text editor or the Markdown editor.

**Comment by StCyr** [comment]
> Nextcloud's Text app unfortunately is incompatible with Pico CMS for Nextcloud. Either use Nextcloud's plain text editor or the Markdown editor.

It's not entirely incompatible: One should just avoid using Text to modify these .md files (and should rather turn to localy editing these files using their favourite text editor rather than using Text). 

I think Markdown Editor and Plain Text Editor are not compatible with NC20.

Anyway, I've figured my way how to use the Pico CMS app and there is no need for further help here.

Thanks for your time
