### ISSUE TITLE
app doesn't support the pico-comments plugin

### ISSUE THREAD

**Issue by StCyr** [nextcloud/cms_pico#151]
Supporting user comments on blogs created with this app would be awesome.

I've tried with https://github.com/push-eax/pico-comments until I've realised it needs to POST the comments to my server (Captain obvious? Yes, it's me)

Unfortunately, cms_pico doesn't support POST.

Do you think it's something that you could support?

**Comment by PhrozenByte** [comment]
Short answer: I'm afraid not, no :unamused: 

Long answer: This plugin relies on creating Markdown files to store comments. This makes totally sense for Pico and is a great database-less solution, however, in the context of Pico CMS for Nextcloud it's a huge issue. The plugin expects a single Pico instance with a single `content` folder and therefore stores comments inside the plugin's folder. However, in Pico CMS for Nextcloud we use a `content` folder per user. Thus we can't store the comments in the plugin's folder (which would otherwise act as some sort of "global comments storage"), but must store it within the Nextcloud storage. However, Nextcloud doesn't just store files on the filesystem, but also caches the folder structure in its database. Nextcloud uses a unique API for filesystem operations. The plugin doesn't know this. You'll have to heavily modify the plugin to meet the special needs of Nextcloud. The fact that the app doesn't accept `POST` requests is the smallest issue I'm afraid

**Comment by StCyr** [comment]
Ok, fair enough. 

unfortunate but totally understandable => closing issue
