### ISSUE TITLE
Split huge strings into separate strings to make them translatable at Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/cms_pico#152]
Reported at Transifex.
See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/308522263?q=issue%3Aopen

The strings are really huge and you cannot handle them without using a third party compare tool.

**Comment by PhrozenByte** [comment]
Any suggestions?

I'm not even sure whether *this particular* string is used. It's the app's description in its `info.xml` ([`appinfo/info.xml` line 9-22](https://github.com/nextcloud/cms_pico/blob/60268edfc2c5a4b3bfab4627c4f956ba4431b76c/appinfo/info.xml#L9-L22)). I guess Nextcloud's i18n tools fetch this string to translate the app store description, but I've no idea how to add the translated descriptions to the app store. @nextcloud/appstore any ideas?

More or less the same strings exist in the app's `README.md` and in the personal settings page. The `README.md` isn't translated and the string in the personal settings page is already split into smaller strings ([`templates/settings.personal.php` line 42-78](https://github.com/nextcloud/cms_pico/blob/60268edfc2c5a4b3bfab4627c4f956ba4431b76c/templates/settings.personal.php#L42-L78)). Still no short strings though, but definitely shorter. I'm not sure whether splitting those strings into even more portions will help much. But, as I said, I'm open for suggestions.

**Comment by rakekniven** [comment]
The app store questions I cannot answer you. Would be a waste of translation power if no one is using the translation.

The smaller portions are already better 👍 

Hopefully someone from app store will respond.

**Comment by rakekniven** [comment]
Just adding a comment to prevent the bot closing it.
The issue is still there.

My suggestion is to shorten the description.

**Comment by PhrozenByte** [comment]
The app store description is the primary source for users to learn about Pico CMS for Nextcloud and whether they want to use the app or not. Thus I don't think that shortening it in a way that would make a difference for translators is feasible.

The weird thing is that the devs of Nextcloud's official translation tool (@MorrisJobke @jakobsack) [explicitly chose to extract the app's description from `info.xml`](https://github.com/nextcloud/docker-ci/blob/f3ad97b91ebecbad729361ba9587341e9b85b663/translations/translationtool/src/translationtool.php#L234-L317) - this is no side effect of a more general implementation, a dev explicitly added code to do this. However, I couldn't find a single app with multilingual descriptions in Nextcloud's app store. So this string appears to be unused. I don't think that this is intentional. We either have

1. an issue with Nextcloud's official translation tool (@nextcloud/docker) extracting useless strings, or
2. an issue with Nextcloud's app store (@nextcloud/appstore) not using these strings.

Since Nextcloud's app store doesn't seem to support translated descriptions anyway, I'm totally fine with removing this string. However, I simply don't know how. I don't think that I can even choose to do so. It's something Nextcloud's official translation tool does.

So, I'm sorry, but I unfortunately can't help you. This is something @nextcloud/appstore and/or @nextcloud/docker have to sort out.

**Comment by rakekniven** [comment]
Hello Daniel,

sorry for the late response. Read your message the first day you wrote it.

You perfectly described the core issue.  👏 

Hello  @MorrisJobke , do you have any comments on here?

**Comment by rakekniven** [comment]
@nickvergessen Will app store use translations in the next future?

**Comment by rakekniven** [comment]
Hello @nextcloud/appstore 

please respond someone.

**Comment by MorrisJobke** [comment]
As of now it's not on the roadmap as we are busy with other stuff. Sorry :/

**Comment by rakekniven** [comment]
Hello Morris, glad to read some notes from you.

If this is not on the roadmap I am asking "why are the strings from info.xml available at Transifex?".

It is a waste of translation power. Can you disable extracting and adding until it is necessary to translate them?

**Comment by MorrisJobke** [comment]
> If this is not on the roadmap I am asking "why are the strings from info.xml available at Transifex?".
> 
> It is a waste of translation power. Can you disable extracting and adding until it is necessary to translate them?

Because they are shown in the app management of the Nextcloud itself. So if the app is downloaded to the Nextcloud server then it shows it in the app management.

**Comment by PhrozenByte** [comment]
That's weird @MorrisJobke, because my Nextcloud shows English descriptions only (not just for `cms_pico`, couldn't find a single app with a non-English description in multiple Nextcloud instances, neither enabled nor disabled or uninstalled). Is there some config that needs to be enabled first? Or are they shown somewhere else (not sure about what you mean by "app management")? Or do you mean some non-public overview?

![grafik](https://user-images.githubusercontent.com/920356/111753447-2a891c00-8897-11eb-8006-5318df0392c8.png)

**Comment by MorrisJobke** [comment]
> That's weird @MorrisJobke, because my Nextcloud shows English descriptions only (not just for `cms_pico`, couldn't find a single app with a non-English description in multiple Nextcloud instances, neither enabled nor disabled or uninstalled). Is there some config that needs to be enabled first? Or are they shown somewhere else (not sure about what you mean by "app management")? Or do you mean some non-public overview?

Mmmh ... back then we I tested it initially it was working 🙈 ™ Maybe something broke in the meantime, because the text there in the sidebar should™ be translated.

**Comment by rakekniven** [comment]
I can confirm it is broken in my NC21.

**Comment by rakekniven** [comment]
Open issue at https://github.com/nextcloud/server/issues/26207

**Comment by PhrozenByte** [comment]
How do we intend to handle this issue now?

We finally know that the strings exist on purpose and should be translated, even though they aren't used right now (nextcloud/server#26207). Making the description shorter so that it makes a difference for translators isn't feasible in my opinion (see above). As described above, the description is already split into separate strings for in-app usage, however, the app store resp. the app management GUI doesn't support splitting the string into multiple parts right now. I don't think that we (as app developer) can do something about this, right? I'd suggest to close this issue then and rather open a feature request on nextcloud/server to support split app descriptions. Needless to say that I'm very happy to use it then :smiley:

**Comment by rakekniven** [comment]
@PhrozenByte Agree 💯 % with you.
