### ISSUE TITLE
Add support for s3 external storage.

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/cms_pico#157]
Hi,

I saw the other issues. I just wanted to open one to track support for it.

Thanks for your work, and for considering this enhancement :)

**Comment by PhrozenByte** [comment]
Pico currently requires direct filesystem access, thus Pico CMS for Nextcloud can't support non-local storages. See #37 for more info. As soon as we have a solution for that, it doesn't really matter what non-local stroage is used, i.e. s3 external storage would work, too. This feature request is tracked in #52

**Comment by pierreozoux** [comment]
if it is already tracked, then I close, just the title of #52 is not really clear.

**Comment by PhrozenByte** [comment]
> just the title of #52 is not really clear.

Yeah, that's because there are currently no plans to add filesystem abstraction to Pico, as it kinda objects the "stupidly simple" approach regarding Pico's own code. Thus it's unlikely that this will be implemented on Pico's side. However, another solution is to let Nextcloud cache external storages locally, allowing Pico to access the files locally. That's what persistent federated data basically is about. Thus it's tracked below #52. It's another solution fore the same problem that is just more likely to be implemented sometime. However, this is nothing we can carry out ourselves. Also see https://github.com/nextcloud/server/issues/8459.

**Comment by pierreozoux** [comment]
Thanks for your kind answer :) have a nice evening :)
