### ISSUE TITLE
The app doesn't respect datadir configuration

### ISSUE THREAD

**Issue by Kixunil** [nextcloud/cms_pico#164]
## Summary

This app doesn't respect datadir configuration making it unusable on high-security instances.

## Steps to reproduce:

1. Install Nextcloud into write-protected location
2. Configure datadir to point to a writable location
3. Install `cms_pico`
4. Attempt to use `cms_pico`

## Expected behavior

`cms_pico` works and places its data into configured datadir

## What happens

Error message complaining about app dir being non-writable.

## Versions

Nextcloud 21
cms_pico: latest stable compatible with NC 21.

Cc @MaxHillebrand

**Comment by PhrozenByte** [comment]
This issue claims various things that require elaboration:

> This app doesn't respect datadir configuration

Pico CMS for Nextcloud uses Nextcloud's configured datadir to manage custom templates, themes, plugins and configs (e.g. `data/appdata_XXXX/cms_pico/themes`). If you change the path of Nextcloud's datadir to a non-default location, the app should use that configured location instead.

> making it unusable on high-security instances

Please elaborate.

**Comment by Kixunil** [comment]
The issue was reported to me by @MaxHillebrand who was asking me for help, please Max, post the exact error message you encountered. I don't have it at hand right now.

>> making it unusable on high-security instances

> Please elaborate.

To prevent hypothetical exploits from overwriting PHP files of Nextcloud, it was installed in read-only location with data dir set to read-write location. All apps are also installed in read-only location. This app attempts to write into its subdirectory, which is write-protected and so it fails.

Making the directory writable destroys this security measure.

**Comment by PhrozenByte** [comment]
Okay, so this issue is not about "respecting datadir configuration", but the fact that Pico CMS for Nextcloud must be able to write to the `apps/cms_pico/appdata_public/` folder.

This is intended behaviour. Files and directories in Nextcloud's datadir aren't published via HTTP(S) for obvious reasons. However, Pico CMS for Nextcloud must somewhere publish public contents like plugin and theme assets (e.g. CSS files), otherwise one couldn't use custom plugins and themes. For this reason the app copies plugin and theme assets to the `apps/cms_pico/appdata_public/` folder, which requires PHP to have write access to this directory.

Making `apps/cms_pico/appdata_public/` writeable doesn't affect any security measures, because only this particular folder needs to be writeable. Anything else can remain read-only, i.e. hypothetical exploits still won't be able to overwrite any of Nextcloud's files.

**Comment by Kixunil** [comment]
Can't PHP just serve those files from datadir? I guess there's some performance improvement by storing it into public directory, right?

The reasoning about only single data dir does seem to make sense, though it's a bit sad having writable files in `/usr`. Is there any restriction against it being a symlink?

> Just to make this clear: Any files written to apps/cms_pico/appdata_public/ must have been uploaded to Nextcloud's datadir via FTP (or similar) first. 

I'm not sure I understand. Does `pico_cms` only copy the files? How is it different from just running `cp`?

**Comment by PhrozenByte** [comment]
> Can't PHP just serve those files from datadir? I guess there's some performance improvement by storing it into public directory, right?

The performance penalty of this would be huge, basically yielding the whole website (including Nextcloud) unresponsive with just a rather small number of concurrent users, because a single user won't just spawn a single PHP process (even though the term "process" isn't quite right for FastCGI and `mod_php`, but makes the issue clearer), but a whole bunch of processes.

> Is there any restriction against it being a symlink?

This is untested, but I can't think of a reason why this shouldn't work. Just give it a try and let us know :smiley:

> Does `pico_cms` only copy the files? How is it different from just running `cp`?

All files are unchanged, but Pico CMS for Nextcloud doesn't just copy *all* files. It only copies files of valid active plugins/themes and copies them to a randomly named sub-directory to improve browser caching.

**Comment by Kixunil** [comment]
@PhrozenByte thanks for clarifications! I will try the symlink approach then. Something bugs me about it but looks like the least bad thing to do. I think it's OK to close this. If symlink doesn't work I will open another issue.
