### ISSUE TITLE
Adding themes is unclear

### ISSUE THREAD

**Issue by johnwry** [nextcloud/cms_pico#180]
I am trying to add a new theme. From the instructions it's supposed to be simple so I'm probably overcomplicating it. 

1.  I go to PICO's site and download a theme (my\_theme)
2.  Upload and unzip 'my\_theme' to PICO's themes directory
3.  Copy the index.twig file from default theme to 'my\_theme' folder
4.  Add 'my\_theme' in the PICO admin section
5.  Change default to 'my\_theme' in my PICO website in the dropdown

....this returns my website without any style.

**Comment by PhrozenByte** [comment]
Unless you want to create your own custom theme I'm not sure why you're copying the default theme's `index.twig`. The theme you've downloaded should already include a `index.twig`. Please note that themes relying on external resources often don't work with Pico CMS for Nextcloud, because the app blocks 3rd party resources by default for security reasons. You'll have to edit the theme to fit your needs then.

**Comment by johnwry** [comment]
Thanks @PhrozenByte , just to make sure,I need to duplicate the default theme folder, rename and adjust accordingly?

**Comment by PhrozenByte** [comment]
If you want to create your own theme: Yes. As an alternative you can also use the "Copy theme" button in the app's admin settings page.

If you want to use a pre-made theme: No. Use the provided `index.twig` - which you can naturally still edit to fit your needs.

**Comment by johnwry** [comment]
Not sure where you "Copy Theme" in the admin page.  That would be great to have in the doc or in a tutorial for newbies.
