### ISSUE TITLE
Comments section for logged users?

### ISSUE THREAD

**Issue by jerabaul29** [nextcloud/cms_pico#191]
Thanks for an amazing project :) .

If I understand well, this makes it very easy to render / serve a static website. But is it possible to have some 'dynamic' aspects to it, like users being able to write comments in a comment section, answering to each others comments etc? If yes, how? If not, do you think this will ever be possible, or is it out of scope?

**Comment by PhrozenByte** [comment]
This rather sounds like a forum and is indeed out of scope of Pico CMS for Nextcloud.

**Comment by jerabaul29** [comment]
Ok, thanks :) .

My 2 cents: it is really useful, also on 'mostly static' websites, to have possibility to have user comments.

Feel free to close, but just being curious: do you know of an easy way to have such a 'forum like' function for users in Nextcloud? :)

**Comment by PhrozenByte** [comment]
Depending on your exact use case there are multiple apps available in Nextcloud's app store that might be a viable solution for you, just skim through the app store.

Just to be a bit more precise here: You could indeed write a Pico plugin to support user comments. I think that user comments kinda run contrary to the idea of having a flat file CMS (there are better solutions if you need this), but that's only my personal opinion. Some devs actually created Pico plugins to support user comments, so it's possible. Just note that none of the existing plugins will work with Nextcloud.

**Comment by jerabaul29** [comment]
Ok, thanks :) .

Just being curious (but if you think this is a too long discussion, just let me know and I stop annoying you :) ), why do you think that flat file CMS is bad for user comments? Do you think it is challenging to process / insert user comments back and forth into a markdown file? (I have no idea how difficult it is, if you say it is difficult I believe you :) ).

**Comment by PhrozenByte** [comment]
> Do you think it is challenging to process / insert user comments back and forth into a markdown file? (I have no idea how difficult it is, if you say it is difficult I believe you :) ).

Basically this. Not in terms of code, this actually is no big deal. The whole idea of a flat file CMS is that we don't want to add the complexity of a database for more or less static content - and a lot (if not most) websites basically serve more or less static content. However, as soon as you want user-generated content (like comments) this is no longer true. For stuff like this one should use a database, simply because that is what they were made for. Always choose the right technology for the problem you want to solve - and for user-generated content a database is the right solution. But Pico is a flat file CMS, thus no database - so...

Besides, there's a lot more to consider, like input sanitization and stuff. Adding user comments would multiply the complexity of Pico - and our main goal is to keep things simple. There's a great number of other awesome CMS out there that simply are a better solution here.

**Comment by jerabaul29** [comment]
Sounds reasonable, feel free to close :) . Wondering if you could provide some pointers at the end of the readme as to what alternative solutions one can look at if user comments are needed, and maybe make this clear in the readme too :) .
