### ISSUE TITLE
Links should use rewritten base URL

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/cms_pico#20]
When setting up a rewritten base URL like /sites/ the generated menu should also make use of it instead of linking to /index.php/apps/cms_pico/pico/...

**Comment by PhrozenByte** [comment]
@daita ⏭ https://github.com/nextcloud/cms_pico/pull/13#issue-260039646

**Comment by daita** [comment]
fixed next release

**Comment by ewilly** [comment]
Could you explain why did you finally revert this in 0.9.6 ? [https://github.com/nextcloud/cms_pico/commit/3ccab6f4c0f226270aad38cb3d1354e6c6a6eebe](url)

**Comment by daita** [comment]
I am not happy right now with the Rewrite, and I will have a deeper look later so in the meanwhile I prefer to still keep the full address that will work in most case.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

This has been fixed in Pico CMS for Nextcloud v1.0.0.
