### ISSUE TITLE
PicoAuth can not work correctly

### ISSUE THREAD

**Issue by LoveWaguan** [nextcloud/cms_pico#204]
I download the plugin "picoauth" and copy to plugins folder, it can be loaded on admin page, but  not work. I wast a lot time to  find "why",it seems picoauth will generate new session after invalid, but picocms hope to keep same session, then session has gone, redirect to valid page again.

**Comment by PhrozenByte** [comment]
Unfortunately we can't provide support for 3rd party plugins here. However, I don't believe that this plugin is compatible with Pico CMS for Nextcloud, but only pure Pico. The PicoAuth plugin requires to initialize a session, the same way Nextcloud does. Since PHP can't have multiple sessions running at once, they will likely interfere with each other. However, you could write a plugin specifically for Pico CMS for Nextcloud to utilize Nextcloud's session instead.

**Comment by LoveWaguan** [comment]
Thanks, i will try to find other ways to resolve this problem.
