### ISSUE TITLE
Crashes after a day, fixable with reboot

### ISSUE THREAD

**Issue by ftastisch** [nextcloud/cms_pico#206]
Hi!

The app stops working each day (not sure yet whether runtime or specific time). Trying to pull up the site results in an nginx error (502 or 504). This is fixed by a reboot for about a day.

The setup is:
- RPi 4, running Manjaro
- nginx and NC24

Disabling/Reinstalling the app in NC did not fix this behaviour. I removed all custom themes and plugins without success. Operating system, NC and all apps are up to date.

Please let me know what additional information might you need if this is not an isolated issue in my setup.

**Comment by PhrozenByte** [comment]
502 Bad Gateway and 504 Gateway Timeout are errors caused by nginx, not by Pico CMS for Nextcloud. I presume you enabled short URLs using `proxy_pass`? I'm no nginx expert and thus can't provide support for it, but a quick [Google search](https://www.google.com/search?q=504+error+nginx) lets me think that the proxy might just time out. Try https://stackoverflow.com/a/36589120 or one of the other solutions provided there.

**Comment by ftastisch** [comment]
Thank you for the hint, I added `proxy_set_header Connection "";`  and will post here if it still works after a day or two.

**Comment by ftastisch** [comment]
Ok, well that did not work, already another 504 this morning. I disabled short URLs completely and restarted nginx to see how it behaves now.

**Comment by killerbees19** [comment]
Take a look at the error logs from Nginx and PHP (FPM?).

If Manjoro uses Systemd: Any failed/crashed services? (`systemctl status …` & `journalctl …`)
