### ISSUE TITLE
copy static website outside of nextcloud

### ISSUE THREAD

**Issue by Sylvain303** [nextcloud/cms_pico#244]
Hello,

I'm discovering both Pico CMS and your NextCloud app. Great job, it works well.
I don't yet how to dive into NextCloud app code. I'm learning...

I would like to know if it would be possible to copy the static website else where on non-NextCloud hosting. A dedicated hosting outside of NextCloud. I suppose a `rsync` would do the job.

Where should I look for customizing the app to handle such behavior?

Regards,
Sylvain.

**Comment by Sylvain303** [comment]
Oh, 😯  I'm wrong!.  Pico cms doesn't generate static website, the `.md` input files are static, not the produced website right?

So my question becomes less obvious. 🤔 ⏳️

**Comment by PhrozenByte** [comment]
As you already noted: Pico is no static website generator.

However, it doesn't have to be, since you need a custom mechanism to copy the website to another server anyway: Simply create a static copy of the website using `wget -r` (possibly `wget -r -k`) and upload the results. That's out of Pico's scope (i.e. no support, just wanted to give you some tip to look for yourself) and not really a Pico-specific approach, you might do exactly the same with any CMS.
