### ISSUE TITLE
Spaces and links

### ISSUE THREAD

**Issue by azmeuk** [nextcloud/cms_pico#26]
Hi. The markdown specification says that a link destination [should not contain spaces](http://spec.commonmark.org/0.28/#links), but sometimes my `.md` files do contain spaces.

It would be great if underscores in a link target could match a space in a markdown file name. For instance if I have a link `[some text](hello_world)`, it would match `hello_world.md` if it exists (exact match first), then `hello world.md` if it exists (underscore space matching).

What do you think?

**Comment by azmeuk** [comment]
Hello @PhrozenByte I see this issue is closed, has it already been solved, or is it not planed at all?

**Comment by PhrozenByte** [comment]
I honestly don't think that this is going to happen, because it would require pretty massive changes. Pico relies on [Parsedown](https://parsedown.org/) to parse Markdown markup, so in the end Pico does what Parsedown does (Markdown-wise at least). If Parsedown resp. the Markdown standard doesn't allow spaces in links we can't really do anything about it without investing a whole lot of work.

Regarding your suggestion to match underscores as spaces, I feel like adding such "magic" isn't really helping. It actually just hides the issue and doesn't really solve it. It rather creates new issues, like what should happen if there's both a `hello world.md` and a `hello_world.md`?

IMHO it's better to simply rename the files to use underscores instead. If you want to keep possibly existing old links with spaces working you can still do so by creating a small Pico plugin that hooks into Pico's `onRequestFile` event. Pico CMS for Nextcloud v1.0.0 fully supports custom plugins (see https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718/16).
