### ISSUE TITLE
Reloading site causes CSRF errors in Nextcloud 

### ISSUE THREAD

**Issue by GregSutcliffe** [nextcloud/cms_pico#29]
Steps to reproduce:
1) Create a PicoCMS site in tab 1
2) Load PicoCMS site in tab 2
3) Make changes to the `index.md` frontpage in tab 1
4) Reload the site in tab 2 to show the changes

This will cause a CSRF failure in tab 1, forcing me to refresh the page before I can continue editing the site.

**Comment by GregSutcliffe** [comment]
Actually, this is worse than i thought. For a "private" site, it's unviewable:

1) Mark site private in Personal Settings (tab1)
2) Load site in tab2
3) Site fails to load - "Website is private. You do not have access to this website"
4) Tab1 is now logged out and needs reloading

I don't seem to be able to load private sites at all. This happens in both Firefox 55 and Chromium 61.

**Comment by daita** [comment]
I could not reproduce the first step, are you sure your session hasn't timed out ?

**Comment by GregSutcliffe** [comment]
100%, I can reproduce this over and over, I logged back 5 times in a row testing it last night. I can probably record a quick video of my desktop to demo it, if it helps.

**Comment by daita** [comment]
And it has nothing to do with your second report regarding private website ?

**Comment by GregSutcliffe** [comment]
You mean #31? No, I've not implemented that yet. My Apache config is just what's recommended:
```
ProxyPass /sites/ https://<mynextcloudserver>index.php/apps/cms_pico/pico/
ProxyPassReverse /sites/ https://<mynextcloudserver>/index.php/apps/cms_pico/pico/
SSLProxyEngine on
```

**Comment by GregSutcliffe** [comment]
So this gets more and more weird - on the same version of Chromium, I can reproduce this 100% on one laptop, and not at all on a different laptop. Any ideas where I can poke it to figure out what's going on?

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Can you please check whether your issue persists with Pico CMS for Nextcloud v1.0.0? I couldn't reproduce it. According to the other comments I assume this being caused by some non-default webserver config interfering. Starting with Pico CMS for Nextcloud v1.0.0 you are no longer required to use the shorter `sites` URLs forcing you to do some webserver config, so you should get it working no matter what. If your issue persists, please open a new Issue here on GitHub.
