### ISSUE TITLE
Cannot display site when pages stored on an external mount local storage

### ISSUE THREAD

**Issue by rkilchmn** [nextcloud/cms_pico#37]
Hi,

I was trying to use Cms Pico App with nextcloud 12. Since i have encryption enabled i had added an un-encrypyed external mount point for local storage. I can edit the .md file on the external storage and can see it is not encrpted.
![external storage](https://user-images.githubusercontent.com/33502448/32762188-ffa5e03a-c94b-11e7-8a15-05607003fc63.png)

Problem I found:
1) An error is displayed that encryption is enabled which is not  true for the external local storage location. The check for encrption need to be specific to the mount point if possible. I guess it is very common to have encryption for user files activated. 
2) I commented out the encryption check but then get another error on the page "Webpage cannot be rendered"

I wouldlike to debug/trace but dont know a good way to output the content of the exception that is thrown in the code

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Storing websites on external storages isn't possible due to technical limitations (if you wanna learn more about the technical limitations, see 41f6228daf15993934994844b0a79560b9ac5cb8). However, the term "external storage" doesn't really match what it really is - so, for example, a server-encrypted Nextcloud is also stored on a "external storage", even though the data is indeed stored on the local disk. It's about how the data is being accessed - either directly or via an abstraction layer. Pico CMS for Nextcloud requires direct file access, thus we'll show a nice error message to inform the user about this issue.

Anyways, you're trying to use a "Local" external storage. A "Local" external storage allows direct file access and thus is no "external storage" in a technical manner. Starting with Pico CMS for Nextcloud v1.0.0 you can indeed use "Local" external storages. However, you won't be able to enable the current beta because of your server-encrypted Nextcloud... However, I'll remove this limitation with the second beta. Your idea of using a "Local" external storage to circumvent the encryption is amazing, I didn't think of this as a solution to support server-encrypted Nextclouds.

Thank you for your help! :+1:

**Comment by rkilchmn** [comment]
Awsome! Will test it out soon

**Comment by rkilchmn** [comment]
I tested with 1.0.0 beta 2 and get an error when selecting the path using a "local" external mount 
"The website's path is stored on a non-local storage."

<img width="416" alt="patherror" src="https://user-images.githubusercontent.com/33502448/69257690-c6c7e380-0bbb-11ea-841d-8592cb5934f3.PNG">
<img width="730" alt="local_external_storage" src="https://user-images.githubusercontent.com/33502448/69257691-c6c7e380-0bbb-11ea-9c7c-deca56b96298.PNG">

**Comment by PhrozenByte** [comment]
Hmm... Weird. I was testing this before and it worked, but now it indeed doesn't work anymore. After checking the code I'm asking myself why it ever worked. Since I had some issues enabling encryption in my Development Nextcloud, I'd assume that encryption never really worked while testing this feature... :unamused: 

Anyway, the issue is that enabling encryption also affects external storages. The "Enable encryption" option of an external storage just tells the storage whether new files should be encrypted, all accesses still use said abstraction layer, making it impossible for Pico CMS for Nextcloud to use this storage. However, since some storages don't support encryption (like the Nextcloud external storage), we can utilize this by registering our own external storage backend that claims that it doesn't support encryption.

Unfortunately I'm currently unable to register said storage backend from the Pico CMS for Nextcloud app (it's just a few lines of code...). The weird thing is: Adding the exact same code to the `files_external` app works just fine. No idea what is going on there... :confused: I'll investigate further and possibly open a bug report for `nextcloud/server`. Since I was planning to release Pico CMS for Nextcloud v1.0.0 this sunday, I don't want this to block the release - it's about time. However, this remains one of the top priorities for Pico CMS for Nextcloud.

**Comment by PhrozenByte** [comment]
Finally got it working, will be in the upcoming `v1.0.2`

**Comment by rkilchmn** [comment]
just testing with latest master. Should i be able to select local storage mount point now? Or is there a different approach now?

**Comment by PhrozenByte** [comment]
You must create and use a "Local (unecrypted)" local storage.

**Comment by rkilchmn** [comment]
Thanks - that did the trick. It is working now!!! Awsome job

**Comment by livier** [comment]
Found the same problen again with pico 1.0.8
I have a folder /var/nextcloud-data out of /var/www/nextcloud.
Is it the source of misunderstanding 
"The website's path is stored on a non-local storage."
And what sould I do ?
