### ISSUE TITLE
Limit to group feature breaks public accessibility

### ISSUE THREAD

**Issue by poVoq** [nextcloud/cms_pico#42]
When you limit the app to groups than pages are not publicly accessible anymore unless you are logged into the nextcloud as a member of the group.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

This is intended behaviour since that's exactly what Nextcloud's "Limit app to group" feature does. However, I know that you've opened this because of #41 - what is a absolutely legit feature request :wink:
