### ISSUE TITLE
is it somehow possible to use <iframes> ?

### ISSUE THREAD

**Issue by Co0p3r21** [nextcloud/cms_pico#44]
I tried to use iFrames an failed. 
First I got error massages on my webbrowser Console regarding CSP. 
To fix it I ajusted my CSP, until no errors were shown in the Browser Console.
I tried very simple Sites in my iFrame e.g. GoogleMaps. 

What am I doing wrong or is it disabled/impossible ?

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Since Pico CMS for Nextcloud allows arbitrary user input, the use of `<iframe>` is disabled due to security reasons. However, you can still use `<iframe>` in custom themes, as long as they don't violate the app's CSP.
