### ISSUE TITLE
Can't pico-cms be used if nc is installed in a subdirectory?

### ISSUE THREAD

**Issue by nursoda** [nextcloud/cms_pico#56]
My NC installation doesn't use its own subdomain but resides in DOMAIN/cloud. Installing PicoCMS is fine but seems not to work correctly since adding a test site yields DOMAIN/sites/test whereas I'd expect it to go to DOMAIN/cloud/sites/test. Actually, DOMAIN/sites/test yields 404.

**Comment by weipah** [comment]
How does your apache config for PicoCMS look like?
Did you make changes according to [the documentation](https://github.com/nextcloud/cms_pico/wiki/Admin-Settings#apache-configuration)?

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

This should be fixed in Pico CMS for Nextcloud v1.0.0. You can check it out now to test whether your issue persists or not. If it does, please open a new Issue here on GitHub.
