### ISSUE TITLE
{"name":"myCloud","error":"Die Adresse der Website darf nur alphanumerische Zeichen enthalten"}

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/cms_pico#59]
{"name":"myCloud","error":"Die Adresse der Website darf nur alphanumerische Zeichen enthalten"}

I've got an alphnumberic Letter in my Nextcloud Web-Address ..so this message means,that PICO is not able to create the Web-Site because of that.

Can this be corrected, because i think .. it's common used, that WEB-Sites does contain alpha-numeric letters.

Thx a lot
Mike

**Comment by PascalHeynmoeller** [comment]
Same message here. Just typed in the address in small letter like "reise" instead of "Reise".
Small letters worked for me to create the page.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

This is intended behaviour, since URLs are indeed case sensitive in theory, but one shouldn't rely on case sensitivity (a webserver running on Windows won't be case sensitive for example...). Having both https://cloud.example.com/sites/my_blog and https://cloud.example.com/sites/my_Blog on a instance is IMO no good solution...
