### ISSUE TITLE
Include  'sudo a2enmod proxy_http' in admin instructions

### ISSUE THREAD

**Issue by GustavoMarcante** [nextcloud/cms_pico#61]
I could not run Pico CMS due to an error.
I looked and could not find anything related do Pico CMS to solve it.
Looking for other similar problems, I realized that it is necessary to include the following command to make it run in a NextCloud install at least in Ubuntu 18.04:
```sudo a2enmod proxy_http```
I suggest to include this in the instructions at:
https://github.com/nextcloud/cms_pico/wiki/Admin-Settings
I could not find a way to do it as a pull request.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

The new webserver configuration instructions now include a note about enabling the required Apache modules. However, we can't directly recommend executing `a2enmod` since this is an Debian-specific command.

Thank you for your help! :+1:
