### ISSUE TITLE
Web site names can't contain Upper case letters

### ISSUE THREAD

**Issue by TerryHewitt** [nextcloud/cms_pico#68]
It appears that website names must NOT contain any uppercase letters.

Website.php has this function:
 public function hasToBeFilledWithValidEntries() {

                $this->hasToBeFilledWithNonEmptyValues();
                $this->pathCantContainSpecificFolders();

                if (MiscService::checkChars($this->getSite(), MiscService::ALPHA_NUMERIC_SCORES) === false) {
                        throw new CheckCharsException(
                                $this->l10n->t('The address of the website can only contains alpha numeric chars')
                        );
                }
        }

That's the error I get when I include an uppercase letter ins the site name/address of the site.

MiscService:checkChars looks at ALPHA_NUMERIC_SCORES

This is from MiscService.php
 const ALPHA_NUMERIC_SCORES = 'abcdefghijklmnopqrstuvwxyz0123456789_-';

Surely this constant should include Upper case letters?

Best wishes

Terry

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

This is intended behaviour, since URLs are indeed case sensitive in theory, but one shouldn't rely on case sensitivity (a webserver running on Windows won't be case sensitive for example...). Having both https://cloud.example.com/sites/my_blog and https://cloud.example.com/sites/my_Blog on a instances is IMO no good solution...

**Comment by TerryHewitt** [comment]
Daniel,

 

OK, on that. But a short note in the documentation (lower case only)  would have helped me!

 

Best wishes

 

Terry

 

Professor W T Hewitt

WTH Associates Ltd

 

Telephone: +44 7905 759 003

 

Company registration number:7336226

HMRC VAT Registration number: 998 8457 23

 

Company Registered Address

St George's House  | 215 - 219 Chester Road | Manchester | M15 4JE

**Comment by PhrozenByte** [comment]
Indeed. Pico CMS for Nextcloud v1.0.0 includes this note :smiley:

>  The identifier of your website prescribes both your website's address (URL) and the name of the directory your website's files (both pages and assets) will be stored in. A website's identifier must consist of lowercase alphanumeric characters, dashes and underscores (a-z, 0-9, - and _) only.
