### ISSUE TITLE
Is there a future for Pico in Nextcloud?????

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [nextcloud/cms_pico#73]
?

**Comment by dcrobertson01** [comment]
I wouldn't use it for anything new :-). At least moving the data (eg markup files) to a standard pico install would be easy.

I'm using GravCMS for new things.

**Comment by PackElend** [comment]
seems to be dead, it's a pitty

**Comment by PackElend** [comment]
> I'm using GravCMS for new things.
how do you get them to run in nextcloud?

**Comment by dcrobertson01** [comment]
I don't 😀 i run it for my stuff with a username and password.I did fork the module so i could take a look at it but thats as far as i got. Its a cool idea. I just don't get that much time--Don Robertson don@robertson.net.nz

-------- Original message --------

**Comment by PackElend** [comment]
>  I just don't get that much time
me too but may I find a student. [GravCMS](https://getgrav.org/) looks a way more promissing than [Pico CMS](http://picocms.org/) in particular in reagard of plug-ins. 
As it comes with an admin dashboard and otehr admin plug-ins, integration in nextcloud should be simpler than for pico CMS, shouldn't it? 

my resources 
https://blog.fortrabbit.com/file-based-cms-2016
https://www.reddit.com/r/selfhosted/comments/7kdkgy/does_anyone_here_use_grav/
https://t3n.de/news/13-kompakte-cms-im-vergleich-461933/

**Comment by PhrozenByte** [comment]
All of this is open source, you can choose whatever CMS you like to use, including writing a app for Nextcloud integrating your favourite CMS in Nextcloud :smiley:

Just about the original question whether there's a future for [Pico](http://picocms.org/) and `cms_pico`: Yes, definitely! Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

**Comment by PackElend** [comment]
> CMS you like to use, including writing a app for Nextcloud integrating your favourite CMS in Nextcloud
would be great if you give some insights on how to integrate 3rd party app like Pico in Nextcloud

> Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release.

that is excellent news

**Comment by PhrozenByte** [comment]
> would be great if you give some insights on how to integrate 3rd party app like Pico in Nextcloud

Actually nothing special :smile: Just check out what `cms_pico` is doing. It all depends on the CMS you want to integrate. Pico makes it very easy to use it as a library (in it's basic form just a `Pico::run()` call), i.e. to integrate it into other projects. For other CMS it might be harder.

**Comment by PackElend** [comment]
> it very easy to use it as a library

so you just as the library to be loaded and pipeline it output/UI into the app window?
In the beta tester call is mentioned that heavy recoding was necessary?

**Comment by dcrobertson01** [comment]
> All of this is open source, you can choose whatever

Yup. If, however, you are a project like Nextcloud, and if you choose cite a feature as a reason for a sector to use Nextcloud (https://nextcloud.com/industries/education/) then you fail to respond to multiple queries about how the feature can be used, your commitment to supporting that sector may be questioned.

By the time this thread was posted, I had already lost interest in the module because of the lack of response. I had posted my experiences in getting it to work, how to get other themes going, Apache config problems and so on and was greeted with a deafening silence. This thread did not get any positive response for several months after it started.

I hope you do get a new version out and solve some of the issues. I think it is a good module to have and is worthwhile. But the other thing about Open Source is that it is a community and you will need help. Ignoring your users won't encourage them to help you.

**Comment by PhrozenByte** [comment]
@dcrobertson01 Please keep in mind that I'm not the original author of this app, that I wasn't related to Nextcloud before and that I just recently took over development. However, if you want something to get done, you'll have to do it yourself. It's open source after all, people are sacrificing their spare time here. This is also true for Nextcloud, just because Nextcloud GmbH exists doesn't mean that one could urge them to do something for free. Just as you don't want others to urge you to do something in your spare time, one should never urge others to do things in their spare time. In my role as Pico's lead developer I was watching the development of this app and was kinda frustrated, too. However, who should I blame? Blaming others not to sacrifice their spare time just isn't fair. I had two options: Either telling people over and over again that I can't help them or take over the project. I did the latter. Solely for fun. And, just to make this clear, I couldn't see anybody else trying to do this.

@PackElend In essence, yes. However, as you can imagine (and by the fact that it's indeed more than just a couple lines of code), you'll have to invest a lot of work in incorporating the CMS with Nextcloud - both in a technical manner - like supporting Nextcloud's storage and routing system, serving theme and plugin assets proberly - and regarding UX, things like management of custom themes and plugins, templates, access control, personal and admin settings pages, etc.
