### ISSUE TITLE
table Markdown not working

### ISSUE THREAD

**Issue by GanenderAD** [nextcloud/cms_pico#74]
When I make a customized template for pico and use markdown to make a table in this template.
It does not render the table like it is supposed to but shows the markdown code as is. like the image shown below.

![Screenshot from 2019-05-08 21-42-52](https://user-images.githubusercontent.com/45031359/57390637-79b19080-71da-11e9-9ad6-b2ae9ed19584.png)

Whereas if you make a website and then try to make a table using markdown through the folder in nextcloud it properly renders the table like it is supposed to. 

Is this a bug or is it supposed to be this way

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Not sure about what the actual issue is. Can you please elaborate further? Themes never affect how Markdown is being rendered. The screenshot you provided looks like your table being enclosed in a code block; either through fenced code blocks (`````` ``` ``````) or by intending the code with spaces (```    ```)

**Comment by muranava** [comment]
can't seem to get tables working either when using pipes and dashes.
by contrast when I try with html <table> it works but any hyperlinks in cells are disabled?
