### ISSUE TITLE
Can't set base_url in config.php

### ISSUE THREAD

**Issue by chrisjq** [nextcloud/cms_pico#76]
base_url from config.php has no effect when set so can't override the default base url for writing links in pico.

e.g.
$config['base_url'] =  = 'https://example.com/";

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Can you please elaborate on why you need to set the `base_url` manually?

**Comment by chrisjq** [comment]
Hey, its more for links created in sites where you might use nginx/apache to redirect a path
If you have a rewrite rule for pico sites at /sites for example

Example with sample site: 

- https://<domain_name>/sites/sample
- If you use %base_url% in the markup you get links back through the non-rewrite rule.
- https://<domain_name>/index.php/apps/cms_pico/pico/sample/sub/index instead of https://<domain_name>/sites/sample/sub/index

**Comment by dewomser** [comment]
> base_url from config.php has no effect when set so can't override the default base url for writing links in pico.
> 
> e.g.
> $config['base_url'] = = 'https://example.com/";

I have found out same thing.
Global variables which are set in  config.php  get emply values in the theme.
--
Themes like "default" are working good.  (no more apache2 workaround needed)

**Comment by PhrozenByte** [comment]
@chrisjq This has been fixed with v1.0.0. Setting `base_url` is no longer necessary, the value is automatically set accordingly to whether a user requested the website through the shorter virtual `sites` folder or through the generic full-application URL (`index.php/apps/cms_pico/pico`).
* If you're navigating to `https://cloud.example.com/sites/example_site/sub/page`, Pico's `base_url` will be `https://cloud.example.com/sites/example_site/`
* If you're rather navigating to `https://cloud.example.com/index.php/apps/cms_pico/pico/example_site/sub/page`, Pico's `base_url` will be ``https://cloud.example.com/index.php/apps/cms_pico/pico/example_site/`.

@dewomser This is an different issue, there's already an feature request for that. See #30

**Comment by wallyreport** [comment]
I cannot find a config.php file at all. Even tried the "find" command.
