### ISSUE TITLE
cms_pico 1.0beta: meta does not work for some tags

### ISSUE THREAD

**Issue by leolivier** [nextcloud/cms_pico#81]
Hi,
I'm testing cms_pico 1.0 beta on nextcloud 16.
I'm trying to create a blog with it and as far as I saw (I didn't test previous versions) it looks like when you wrote:
```
---
Title: Man must explore, and this is exploration at its greatest
Description: Problems look mighty small from 150 miles up
Date: 11 June 2016
Author: Mohamed Safouan Besrour
Profile: http://besrourms.github.io
Img: https://unsplash.it/1200/628?image=1075
Template: post
---
```
then in your post.twig template a line like this one should work:
`<header class="intro-header" style="background-image: {% if meta.img %} url({{ meta.img }}) {% else %} url('{{ theme_url }}/img/post-bg.jpg'){% endif %};">`

but it doesn't: {{meta.img}} returns void...
Same for {{meta.profile}} btw. I checked this by adding the following lines in the template:
`<p>title={{meta.title}}, img={{meta.img}}, profile={{meta.profile}}, template={{meta.template}}</p>
`
which for the case above displays:
**title=Man must explore, and this is exploration at its greatest, img=, profile=, template=post**
I didn't invent any of this code lines, they are coming from clean-blog theme that seemed to work in previous versions...
Is this a bug or am I doing something wrong?

**Comment by PhrozenByte** [comment]
No, you didn't do anything wrong. `clean-blog` was made for Pico 1.0 and prior to Pico 2.0, all meta headers were lowered unsolicited (i.e. `Img: https://unsplash.it/1200/628?image=1075` was accessible via `{{ meta.img }}`). However, this was inconsistent with keys on any deeper level, thus we stopped lowering keys with Pico 2.0 (unless explicitly told for using using Pico's `onMetaHeaders` event). Thus you'll have to use `{{ meta.Img }}` now, i.e. matching exactly the header's name (including case).

In a regular Pico installation you won't notice any difference, because Pico's official `PicoDeprecated` plugin takes care of this situation. However, Pico CMS for Nextcloud didn't use `PicoDeprecated` until now. I'm currently working on splitting `PicoDeprecated` functionality into multiple, version-specific plugins, allowing us to integrate just the necessary tweaks to maintain BC with Pico 1.0.

To cut a long story short: This will be fixed in beta 2.
