### ISSUE TITLE
Layout should not use tables

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/cms_pico#9]
For that reason all elements get highlighted on hover (even the paragraphs).

![bildschirmfoto 2017-09-20 um 11 18 36](https://user-images.githubusercontent.com/245432/30636349-79dff778-9df5-11e7-8680-813a589b1232.png)

cc @nextcloud/designers

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

This has been fixed with Pico CMS for Nextcloud v1.0.0.
